#docker run -d --name my_postgres -e POSTGRES_PASSWORD=docker -v my_dbdata:/var/lib/postgresql/data -p 54320:5432 postgres:11

version: '3'

services:

  testdb:
    image: postgres
    restart: always
    ports:
      - "54329:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - test_db:/var/lib/postgresql/data

  testdb_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  test_db:


